### PR TITLE
Profanity filter

### PR DESCRIPTION
**Pull request by mollerhoj**
Beginning of a very simple profanity filter.

https://arxiv.org/abs/2112.11446 uses googles "safe search" which is not applicable here.

Thoughts:
- I couldn't find a list of safe danish domains. I don't think we can just use an international one, because looking at the texts, I believe most of the adult material here come from:
- A) Small, rather fringe sites (highly SEO optimized sites that try to lure in customers by targeting specific sexual preferences).
- B) Escort sites offering their services in specific cities (Esbjerg was a very common word). My guess is that since prostitution is legal in Denmark, the Danish web has an overrepresentation of this kind of stuff that targets sex tourism.
- I couldn't find a comprehensive wordlist, so instead I found about 20 seed words, and then bootstrapped from there (manually adding words from the documents found by using this filter). Hence no source.
- Regarding specific biases, I believe the best way forward would be to actually classify the sites and train a classifier? The wordlist here is still very useful for manually finding pornographic sites for such a data set. A simpler approach would to just remove the troublesome words mentioned, or manually add a weight to them, and use that.
- Perhaps we could use the classifier to create a list of domains to block - I'm not sure how many candidates we would end up with, but maybe its small enough that its possible to manually curate it?

Todo:
- Choose a better heuristic
- Expand wordlist (include english list also)
- Run tests

On a site note: Do remember that all filtering adds extra bias to any data set. What might seem politically correct or in good taste is in no way a reflection of any objective truth - only the moral whims of the time. We should of course try to avoid false positives. If the goal is to build an AI that can be used in commercial settings, censoring on specific words makes sense because that the usual technique used by nsfw filters - The American television *biip* sound comes to mind.

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
This seems to be a work in progress so for now I will just convert it to a draft.

A note on this from the Gopher paper (emphasis added):

> Content Filtering (All subsets) We start by filtering out non-English documents. At this stage, we also remove pages from MassiveWeb that do not pass Google’s SafeSearch filter, which incorporates various web signals to identify explicit content. **We use SafeSearch rather than manual word-list filters because the latter have been found to disproportionately filter out inoffensive content associated with minority groups (Dodge et al., 2021).**

referring to: https://arxiv.org/abs/2104.08758

This code is still useful, but we should probably think about how to circumvent that problem, for example, include domains - i.e. such that if a domain consistently (90% of the domain) contain n or more "unsafe" words then filter out all of the domain? We can probably validate this approach using some online list of unsafe domains? (which I assume exist)

@martbern is working on a generalized version of match lookup using the spaCy match object. We will put up a draft PR later today. This can probably be reworked into that workflow.

regarding the word list, it does seem to contain some problematic words (i.e. "kvinder", "bøsse", "latino"), do we have a source on that word list?

**Comment by martbern** [comment]
Just to expand on @KennethEnevoldsen - we'd probably want to avoid terms which are "false positives". 

E.g. while porn might include words like "latino" more frequently than other docs, so would texts about latino rights. This might bias against minorities.

**Comment by KennethEnevoldsen** [comment]
- Re. domains: Thanks for taking a look I will also ask the royal library if they have a list. I don't believe any list would be comprehensive though.
- Applying a classifier or a word list count would both be fine by me. I think you are right that moving on applying a filter and then finding porn sites candidates is probably the way to go. (potentially we could do it on a small subsection of the corpus).

**Comment by KennethEnevoldsen** [comment]
Hej @mollerhoj har kigget en del mere på dette her i dag:

Tror jeg vil foreslå løsningen noget alla:
- Find garanteret pornografiske sider hvis de indeholder "hårde" (e.g. sex ikke amatør) pornografiske ord i domænenavnet
- Lyder til vi har data på referencer så vi kan lave en regel om hvis en side refereres mere til af pornografiske sider end en ikke-pornografiske sider så er det en pornografiske side
- Ud fra et sample lav en liste af de sider med antallet af pornografiske ord. Manuelt opdatér listen of pornografiske sider ellers lav et cutoff

Hvordan lyder dette?

**Comment by KennethEnevoldsen** [comment]
> > Hej @mollerhoj har kigget en del mere på dette her i dag:
> > Tror jeg vil foreslå løsningen noget alla:
> > 
> > * Find garanteret pornografiske sider hvis de indeholder "hårde" (e.g. sex ikke amatør) pornografiske ord i domænenavnet
> 
> Jeg ville holde mig fra dette. Det er overraskende svært at gætte rigtigt med denne slags regler. Stor del af mine false positives var lægefaglige - sexogsamfund.dk vil vi jo gerne have med, men den ville blive ramt ^. Domænenavnet er for mig at se alt for lidt info til at gætte hvad en side handler om (ihvertfald for en computer).

Godt set, er enig at denne metode helt sikkert kan være problematisk. Lad os ikke gøre det.

Jeg har brugt noget mere tid på at kigge på dette og opdagede denne pakke:
https://github.com/MarioVilas/googlesearch

De har en "safe" (search) argument som bruger googles safe search, så idéen er basically at søge på alle domæner med og uden safe search og se hvilke der bliver fjernet. Alle de sider må så være "unsafe". Tænker det er en bedre metode helt generelt. Noget alla:
```
>>> from googlesearch import search
>>> potential_sites = list(search("pornhub.com", num=10, stop=10))
>>> potentialt_sites
['https://www.pornhub.com/', 'https://xxx-porn-hub.com/', 'https://similar.porn/s/4/pornhub.com/', 'http://wwwpornhub.pro/', 'https://www.pornhubpremium.com/', 'https://www.pornohut.info/', 'https://porn62.com/www-pornhub-com-black-fucks-missreinat-big-hd-porner-dick/', 'https://porn62.com/pormhub-stepmother-www-pornhub-com-fucks-stepson/', 'https://theporndude.com/566/pornhub', 'https://de.wikipedia.org/wiki/Pornhub']
>>> safe_sites = set(search("pornhub.com", num=10, stop=10, safe="on"))
>>> safe_sites
['https://www.semrush.com/blog/most-visited-websites/', 'https://www.similarweb.com/top-websites/denmark/', 'http://leifshows.dk/2016/10/03/danskernes-20-mest-populaere-websider/', 'https://www.quora.com/Are-all-USB-%F0%9D%91%BF%F0%9D%92%99%F0%9D%92%99-%F0%9D%92%84%F0%9D%92%90%F0%9D%92%8E-%F0%9D%91%9D%F0%9D%91%9C%F0%9D%91%9F%F0%9D%91%9B%E2%84%8E%F0%9D%91%A2%F0%9D%91%8F-%F0%9D%92%84%F0%9D%92%90%F0%9D%92%8E', 'https://www.wipo.int/amc/en/domains/search/text.jsp?case=DDO2021-0001', 'https://www.wipo.int/amc/en/domains/casesx/list.jsp?prefix=DDO&year=2021&seq_min=1&seq_max=199', 'https://www.palmdalesd.org/Page/5774', 'https://whynoipv6.com/', 'https://www.campagion.com/', 'https://vsco.co/xyz-xyz2']
```

**Comment by mollerhoj** [comment]
Okay, at bruge safe search vi jo være at overlade filteringsarbejdet til google. Nedenfor er de pro/cons jeg ser. Uddyb gerne med flere hvis der er noget jeg har overset - så kan vi vælge hvilken løsning der er bedst:

Pros:
- Ville sandsynligvis bruge mere avancerede teknikker til at sørge for at siderne ikke indeholder pornografi.
- Vi ville ikke selv skulle gøre arbejdet med at bygge et filter.
- Lettere at undgå at vi introducerer fejl.
- Kan bruges på alle sprog
- Er blevet brugt tidligere i papers (fra Google)

Cons:
- Da vi kun er interessede i teksten, kan det være at google's filter indeholder false positives: F.eks sider med mange NSFW billeder som google måske fanger pga. billede analysen, men hvor teksten er god nok. Eller måske har safe search simpelthen en anden definition af hvad der er "safe" (amerikansk kultur er typisk en anelse mere puritansk end dansk på visse områder). Er bettingsider "safe"? Sider med vold?
- Jeg er nervøs for om det kan gå tilstrækkeligt hurtigt - hvad er rate limits på apiet?
- Jeg er nervøs for der var en grænse på antallet af api kald, kender vi hard limits, og skal man betale for at bruge det?
- Løsningen bliver mindre generisk da man jo skal kende en "url" og ikke kan filtere arbitrær tekst.
- Løsningen er jo pragmatisk, men måske ikke så god i en akademisk sammenhæng? (Kan ikke replikeres, ændre sig over tid, er i Googles hænder)
- Måske en generel aversion imod at lade Google diktere hvad der er safe/ikke safe (ellers er det jo self bare os der dikterer, men det jo et typisk EU argument, så jeg tog det med).

**Comment by KennethEnevoldsen** [comment]
> Cons:
> 
> * Da vi kun er interessede i teksten, kan det være at google's filter indeholder false positives: F.eks sider med mange NSFW billeder som google måske fanger pga. billede analysen, men hvor teksten er god nok. Eller måske har safe search simpelthen en anden definition af hvad der er "safe" (amerikansk kultur er typisk en anelse mere puritansk end dansk på visse områder). Er bettingsider "safe"? Sider med vold?
> * Løsningen er jo pragmatisk, men måske ikke så god i en akademisk sammenhæng? (Kan ikke replikeres, ændre sig over tid, er i Googles hænder)

When filtering let us create a list of unsafe domains which we have filtered and validate, 100-200 of them. This will also be a documentation of what is removed. However, I agree that it isn't the ideal solution, but any solution we could make in a reasonable amount of time is probably worse.

> * Jeg er nervøs for om det kan gå tilstrækkeligt hurtigt - hvad er rate limits på apiet?
> * Jeg er nervøs for der var en grænse på antallet af api kald, kender vi hard limits, og skal man betale for at bruge det?
Not sure, but the idea is to create a counter of domains and then just look up the domain (i.e. look up porn.dk instead of porn.dk/blabla...). So we will strongly limit the API calls.


> * Måske en generel aversion imod at lade Google diktere hvad der er safe/ikke safe (ellers er det jo self bare os der dikterer, men det jo et typisk EU argument, så jeg tog det med).

Def. agree with this one. It is def. one of the steps I would like to dive deeper into in version two of this corpus.

**Comment by KennethEnevoldsen** [comment]
Bare lige et eksempel med en hjemmeside som potentielt kunne være problematisk:

```
>>> from googlesearch import search
>>> potential_sites = list(search("sexogsamfund.com", num=10, stop=10, lang="da"))
>>> potential_sites
['http://sexogsamfund.com/', 'https://www.sexogsamfund.dk/undervisning', 'https://www.sexogsamfund.dk/ugesex', 'https://www.sexogsamfund.dk/ledige-stillinger', 'https://www.sexogsamfund.dk/praeventionsklinik', 'https://www.sexogsamfund.dk/kontakt-os', 'https://www.sexogsamfund.dk/hvem-er-vi', 'https://www.sexogsamfund.dk/hvem-er-vi/sekretariat', 'https://www.facebook.com/sexogsamfund/', 'https://www.underviserportal.dk/grundskole/materialer/']
>>> potential_sites = list(search("sexogsamfund.com", num=10, stop=10, lang="da", safe="on"))
>>> potential_sites
['http://sexogsamfund.com/', 'https://www.sexogsamfund.dk/undervisning', 'https://www.sexogsamfund.dk/ugesex', 'https://www.sexogsamfund.dk/ledige-stillinger', 'https://www.sexogsamfund.dk/praeventionsklinik', 'https://www.sexogsamfund.dk/kontakt-os', 'https://www.sexogsamfund.dk/hvem-er-vi', 'https://www.sexogsamfund.dk/hvem-er-vi/sekretariat', 'https://www.facebook.com/sexogsamfund/', 'https://www.underviserportal.dk/grundskole/materialer/']
```

**Comment by mollerhoj** [comment]
@KennethEnevoldsen I would be surprised if we can look up virtually all dk domains without hitting googles limits: https://github.com/MarioVilas/googlesearch/issues/98

**Comment by martbern** [comment]
@mollerhoj I know @KennethEnevoldsen has applied for research-access to the [Google Safe Search API](https://developers.google.com/safe-browsing/v4) 👍

**Comment by mollerhoj** [comment]
> Beginning of a very simple profanity filter.
> 
> https://arxiv.org/abs/2112.11446 uses googles "safe search" which is not applicable here.
> 
> Thoughts:
> 
> * I couldn't find a list of safe danish domains. I don't think we can just use an international one, because looking at the texts, I believe most of the adult material here come from:
> * A) Small, rather fringe sites (highly SEO optimized sites that try to lure in customers by targeting specific sexual preferences).
> * B) Escort sites offering their services in specific cities (Esbjerg was a very common word). My guess is that since prostitution is legal in Denmark, the Danish web has an overrepresentation of this kind of stuff that targets sex tourism.
> * I couldn't find a comprehensive wordlist, so instead I found about 20 seed words, and then bootstrapped from there (manually adding words from the documents found by using this filter). Hence no source.
> * Regarding specific biases, I believe the best way forward would be to actually classify the sites and train a classifier? The wordlist here is still very useful for manually finding pornographic sites for such a data set. A simpler approach would to just remove the troublesome words mentioned, or manually add a weight to them, and use that.
> * Perhaps we could use the classifier to create a list of domains to block - I'm not sure how many candidates we would end up with, but maybe its small enough that its possible to manually curate it?
> 
> Todo:
> 
> * Choose a better heuristic
> * Expand wordlist (include english list also)
> * Run tests
> 
> On a site note: Do remember that all filtering adds extra bias to any data set. What might seem politically correct or in good taste is in no way a reflection of any objective truth - only the moral whims of the time. We should of course try to avoid false positives. If the goal is to build an AI that can be used in commercial settings, censoring on specific words makes sense because that the usual technique used by nsfw filters - The American television _biip_ sound comes to mind.

**Pull request closed without merging**
