### PR TITLE
docs: Added user-friendly tutorial for qlora

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**

### CODE REVIEW

**Review by saattrupdan — COMMENTED** [review]
Don't really understand. It seems like the `finetune_qlora` notebook is meant to replace the `finetune` notebook, as both are QLoRa finetuning decoder models, but the new one is more user friendly. What's the point of the old one?

**Comment by KennethEnevoldsen** [comment]
Well since it is a blog post I don't want to break any links. For practitioners the old one might also be more application-friendly(more memory efficient with less boilerplate and more config objects). I think both are relevant.

**Comment by saattrupdan** [comment]
> Well since it is a blog post I don't want to break any links. For practitioners the old one might also be more application-friendly(more memory efficient with less boilerplate and more config objects). I think both are relevant.

But it's not a blog post, it's a new notebook. I'm all for writing new blog posts, but shouldn't we just update the existing notebook and make a new blog post about it? No links are broken then. Having two notebooks doing exactly the same thing just seems super confusing.

**Comment by KennethEnevoldsen** [comment]
blog post == notebook (at least in our case)

We can def. also update the previous one. I would be totally be up for that as well though I would probably just replace it with the current one. There are however a few cases the previous notebook cover which this one does not (export to other formats)

**Comment by KennethEnevoldsen** [comment]
I am gonna merge this in

**Pull request merged**
